eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

microservice:
   payment-service:
       endpoints:
          endpoint:
             uri: http://PAYMENT-SERVICES/payment/doPayment
   order-service:
       endpoints:
          endpoint:
             uri: http://ORDER-SERVICES/order/bookOrder
